version: '3.8'
services:
  backend:
    image: ghcr.io/broccoproject/admin_backend:latest
    container_name: admin_panel_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL_ADMIN=${DATABASE_URL_ADMIN}
    env_file:
      - /app/.env

  caddy:
    image: caddy:2-alpine
    container_name: caddy_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    command: caddy reverse-proxy --from https://${DOMAIN} --to http://backend:8000
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
