"""fix recipe constraints, add user completed node and category models

Revision ID: 6f32326ff224
Revises: 02e32a65ded4
Create Date: 2026-05-16 22:02:15.714774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f32326ff224'
down_revision: Union[str, Sequence[str], None] = '02e32a65ded4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('profiles_id_fkey'), 'profiles', type_='foreignkey')
    op.drop_constraint(op.f('roadmap_nodes_recipe_id_fkey'), 'roadmap_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'roadmap_nodes', 'recipes', ['recipe_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmap_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('roadmap_nodes_recipe_id_fkey'), 'roadmap_nodes', 'recipes', ['recipe_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('profiles_id_fkey'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth')
    # ### end Alembic commands ###
