"""add admin_auth schema tables

Revision ID: 7e3e6f42e1c5
Revises: 962bd7707944
Create Date: 2026-05-23 19:54:37.495807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.

revision: str = '7e3e6f42e1c5'
down_revision: Union[str, Sequence[str], None] = '962bd7707944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS admin_auth")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('editor', 'admin', name='admin_role', schema='admin_auth'), server_default='editor', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_auth.admin_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='admin_auth'
    )
    op.create_table('access_requests',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='access_request_status', schema='admin_auth'), server_default='pending', nullable=False),
    sa.Column('token', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now() + interval '48 hours'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['admin_auth.admin_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='admin_auth'
    )
    op.create_index('ix_admin_auth_access_requests_user_id_pending', 'access_requests', ['user_id'], unique=True, schema='admin_auth', postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_auth_access_requests_user_id_pending', table_name='access_requests', schema='admin_auth', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('access_requests', schema='admin_auth')
    op.drop_table('admin_profiles', schema='admin_auth')
    op.execute("DROP TYPE IF EXISTS admin_auth.admin_role")
    op.execute("DROP TYPE IF EXISTS admin_auth.access_request_status")
    op.execute("DROP SCHEMA IF EXISTS admin_auth")
    # ### end Alembic commands ###
