"""remove google_sub from access_requests

Revision ID: 38f604aea78d
Revises: c3ecc3aae719
Create Date: 2026-05-24 15:15:37.116341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f604aea78d'
down_revision: Union[str, Sequence[str], None] = 'c3ecc3aae719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_requests_google_sub_pending'), table_name='access_requests', postgresql_where="(status = 'pending'::access_request_status)")
    op.create_index('ix_access_requests_email_pending', 'access_requests', ['email'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.drop_column('access_requests', 'google_sub')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_requests', sa.Column('google_sub', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_access_requests_email_pending', table_name='access_requests', postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_access_requests_google_sub_pending'), 'access_requests', ['google_sub'], unique=True, postgresql_where="(status = 'pending'::access_request_status)")
    # ### end Alembic commands ###
