"""add profile_id to access_requests

Revision ID: 47ca11f61414
Revises: 56fd3fd9a554
Create Date: 2026-05-30 22:43:25.317119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ca11f61414'
down_revision: Union[str, Sequence[str], None] = '56fd3fd9a554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_requests', sa.Column('profile_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'access_requests', 'admin_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access_requests', type_='foreignkey')
    op.drop_column('access_requests', 'profile_id')
    # ### end Alembic commands ###
