"""remove email unique constraint

Revision ID: 56fd3fd9a554
Revises: 28db58a80a74
Create Date: 2026-05-30 22:33:54.835137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fd3fd9a554'
down_revision: Union[str, Sequence[str], None] = '28db58a80a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('admin_profiles_email_key'), 'admin_profiles', type_='unique')
    op.create_unique_constraint('uq_admin_profiles_email_provider', 'admin_profiles', ['email', 'auth_provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_admin_profiles_email_provider', 'admin_profiles', type_='unique')
    op.create_unique_constraint(op.f('admin_profiles_email_key'), 'admin_profiles', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
