"""add google_sub to admin_profiles

Revision ID: c3ecc3aae719
Revises: aa362f860586
Create Date: 2026-05-24 14:33:20.281803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ecc3aae719'
down_revision: Union[str, Sequence[str], None] = 'aa362f860586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_requests', sa.Column('google_sub', sa.String(), nullable=False))
    op.drop_index(op.f('ix_access_requests_user_id_pending'), table_name='access_requests', postgresql_where="(status = 'pending'::access_request_status)")
    op.create_index('ix_access_requests_google_sub_pending', 'access_requests', ['google_sub'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.drop_column('access_requests', 'user_id')
    op.add_column('admin_profiles', sa.Column('google_sub', sa.String(), nullable=True))
    op.drop_constraint(op.f('admin_profiles_user_id_key'), 'admin_profiles', type_='unique')
    op.create_unique_constraint(None, 'admin_profiles', ['google_sub'])
    op.drop_column('admin_profiles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_profiles', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin_profiles', type_='unique')
    op.create_unique_constraint(op.f('admin_profiles_user_id_key'), 'admin_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('admin_profiles', 'google_sub')
    op.add_column('access_requests', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index('ix_access_requests_google_sub_pending', table_name='access_requests', postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_access_requests_user_id_pending'), 'access_requests', ['user_id'], unique=True, postgresql_where="(status = 'pending'::access_request_status)")
    op.drop_column('access_requests', 'google_sub')
    # ### end Alembic commands ###
