"""add viewer role

Revision ID: ebcf3a6d4d4f
Revises: 38f604aea78d
Create Date: 2026-05-25 14:18:43.084004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcf3a6d4d4f'
down_revision: Union[str, Sequence[str], None] = '38f604aea78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE admin_role ADD VALUE IF NOT EXISTS 'viewer'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
